#!/usr/bin/env bash
# generate-agents-md.sh — Compile AGENTS.md from project CLAUDE.md + referenced skills.
#
# Usage:
#   generate-agents-md.sh <project-path> [--dry-run]
#
# Reads:  <project>/.claude/CLAUDE.md, ~/.claude/CLAUDE.md, ~/.claude/skills/<name>/SKILL.md
# Writes: <project>/AGENTS.md (or stdout if --dry-run)

set -euo pipefail

GLOBAL_CLAUDE="${HOME}/.claude/CLAUDE.md"
SKILLS_DIR="${HOME}/.claude/skills"

# --- Argument parsing ---
PROJECT_PATH="${1:-}"
DRY_RUN=false
[[ "${2:-}" == "--dry-run" ]] && DRY_RUN=true

if [[ -z "$PROJECT_PATH" ]]; then
  echo "Usage: generate-agents-md.sh <project-path> [--dry-run]" >&2
  exit 1
fi

PROJECT_PATH="${PROJECT_PATH%/}"
PROJECT_CLAUDE="${PROJECT_PATH}/.claude/CLAUDE.md"

if [[ ! -f "$PROJECT_CLAUDE" ]]; then
  echo "Error: ${PROJECT_CLAUDE} not found" >&2
  exit 1
fi

TMPFILE=$(mktemp)
trap 'rm -f "$TMPFILE"' EXIT

# --- Functions ---

# Extract content between a ## heading and the next ## heading
extract_section() {
  local file="$1" heading="$2"
  awk -v h="## ${heading}" '
    $0 == h { found=1; next }
    found && /^## / { exit }
    found { print }
  ' "$file"
}

# Extract all project sections except Relevant Skills
extract_project_sections() {
  local file="$1"
  awk '
    /^## Relevant Skills/ { skip=1; next }
    skip && /^## / { skip=0 }
    skip { next }
    { print }
  ' "$file"
}

# Parse skill names from Relevant Skills table (backtick-quoted in column 1)
parse_skill_refs() {
  local file="$1"
  awk '
    /^## Relevant Skills/ { found=1; next }
    found && /^## / { exit }
    found { print }
  ' "$file" \
    | { grep -oE '`[a-zA-Z][a-zA-Z0-9-]+`' || true; } \
    | tr -d '`' \
    | sort -u
}

# Read SKILL.md, strip frontmatter/Claude-specific, demote all headings by +2 levels
strip_skill_content() {
  local file="$1"
  awk '
    NR==1 && /^---$/ { in_front=1; next }
    in_front && /^---$/ { in_front=0; next }
    in_front { next }
    /^## Integration/ { skip_section=1; next }
    skip_section && /^## / { skip_section=0 }
    skip_section { next }
    /^\*\*Announce at start:\*\*/ { next }
    /superpowers:/ { next }
    /^##### / { sub(/^##### /, "####### "); print; next }
    /^#### / { sub(/^#### /, "###### "); print; next }
    /^### / { sub(/^### /, "##### "); print; next }
    /^## / { sub(/^## /, "#### "); print; next }
    /^# [^#]/ { sub(/^# /, "#### "); print; next }
    { print }
  ' "$file"
}

# --- Assemble to temp file ---

{
  echo "<!-- Auto-generated by generate-agents-md.sh. Do not edit manually. -->"
  echo "<!-- Regenerate: ~/.claude/tools/generate-agents-md.sh ${PROJECT_PATH} -->"
  echo ""

  # Project sections (everything except Relevant Skills)
  extract_project_sections "$PROJECT_CLAUDE"

  # Global code standards
  echo ""
  echo "## Code Standards"
  echo ""
  extract_section "$GLOBAL_CLAUDE" "Code Principles"

  # Global git conventions
  echo ""
  echo "## Git Conventions"
  echo ""
  extract_section "$GLOBAL_CLAUDE" "Git Commits (Strictly Enforced)"

  # Global error handling
  echo ""
  echo "## Error Handling"
  echo ""
  extract_section "$GLOBAL_CLAUDE" "Error Handling Philosophy"

  # Inline referenced skills
  skill_refs=$(parse_skill_refs "$PROJECT_CLAUDE")
  if [[ -n "$skill_refs" ]]; then
    echo ""
    echo "## Skill Reference"

    while IFS= read -r skill_name; do
      skill_file="${SKILLS_DIR}/${skill_name}/SKILL.md"
      if [[ ! -f "$skill_file" ]]; then
        echo "Warning: Skill '${skill_name}' not found at ${skill_file}" >&2
        continue
      fi
      echo ""
      echo "### ${skill_name}"
      echo ""
      strip_skill_content "$skill_file"
      echo ""
      echo "---"
    done <<< "$skill_refs"
  fi

  # Footer
  echo ""
  echo "*Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)*"
} > "$TMPFILE"

# --- Skill refs (needed for staleness check and count) ---
skill_refs=$(parse_skill_refs "$PROJECT_CLAUDE")

# --- Count skills compiled ---
skills_compiled=$(echo "$skill_refs" | while IFS= read -r s; do
  [[ -f "${SKILLS_DIR}/${s}/SKILL.md" ]] && echo "$s"
done | wc -l | tr -d ' ')

# --- Output ---

if $DRY_RUN; then
  cat "$TMPFILE"
else
  output_file="${PROJECT_PATH}/AGENTS.md"

  # --- Staleness check (before overwriting) ---
  if [[ -f "$output_file" ]]; then
    agents_mtime=$(stat -f %m "$output_file" 2>/dev/null || stat -c %Y "$output_file" 2>/dev/null)
    stale_count=0

    claude_mtime=$(stat -f %m "$PROJECT_CLAUDE" 2>/dev/null || stat -c %Y "$PROJECT_CLAUDE" 2>/dev/null)
    if [[ "$claude_mtime" -gt "$agents_mtime" ]]; then stale_count=$((stale_count + 1)); fi

    global_mtime=$(stat -f %m "$GLOBAL_CLAUDE" 2>/dev/null || stat -c %Y "$GLOBAL_CLAUDE" 2>/dev/null)
    if [[ "$global_mtime" -gt "$agents_mtime" ]]; then stale_count=$((stale_count + 1)); fi

    while IFS= read -r skill_name; do
      skill_file="${SKILLS_DIR}/${skill_name}/SKILL.md"
      if [[ ! -f "$skill_file" ]]; then continue; fi
      skill_mtime=$(stat -f %m "$skill_file" 2>/dev/null || stat -c %Y "$skill_file" 2>/dev/null)
      if [[ "$skill_mtime" -gt "$agents_mtime" ]]; then stale_count=$((stale_count + 1)); fi
    done <<< "$skill_refs"

    if [[ "$stale_count" -gt 0 ]]; then
      echo "  Was stale: ${stale_count} source(s) changed since last generation"
    fi
  fi

  cp "$TMPFILE" "$output_file"
  line_count=$(wc -l < "$output_file" | tr -d ' ')
  echo "Generated: ${output_file}"
  echo "  Skills compiled: ${skills_compiled}"
  echo "  Line count: ${line_count}"
  if [[ "$line_count" -gt 500 ]]; then
    echo "  Warning: Output exceeds 500 lines. Consider trimming skill references."
  fi
fi
